apiVersion: v1
kind: Secret
metadata:
  name: debugmate-local-secrets
  namespace: debugmate-local
type: Opaque
stringData:
  OPENSEARCH_INITIAL_ADMIN_PASSWORD: LocalDevPassword123!
  OPENSEARCH_URL: http://opensearch:9200
  CELERY_BROKER_URL: redis://redis:6379/0
