apiVersion: apps/v1
kind: Deployment
metadata:
  name: debugmate-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: debugmate-api
  template:
    metadata:
      labels:
        app: debugmate-api
    spec:
      containers:
        - name: debugmate-api
          image: debugmate-api:local
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          env:
            - name: DEBUG
              value: "true"
            - name: ENVIRONMENT
              value: "local"
            - name: CELERY__BROKER_URL
              valueFrom:
                secretKeyRef:
                  name: debugmate-local-secrets
                  key: CELERY_BROKER_URL
            - name: CELERY__QUEUE_NAME
              value: "debugmate-queue"
            - name: OPENSEARCH__URL
              valueFrom:
                secretKeyRef:
                  name: debugmate-local-secrets
                  key: OPENSEARCH_URL
            - name: OPENSEARCH__USE_SSL
              value: "false"
            - name: OPENSEARCH__VERIFY_CERTS
              value: "false"
            - name: OPENSEARCH__SSL_ASSERT_HOSTNAME
              value: "false"
            - name: OPENSEARCH__SSL_SHOW_WARN
              value: "false"
          livenessProbe:
            httpGet:
              path: /health/live
              port: 8000
            initialDelaySeconds: 20
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 8000
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 10
            failureThreshold: 5