apiVersion: apps/v1
kind: Deployment
metadata:
  name: localstack
  namespace: debugmate-local
spec:
  replicas: 1
  selector:
    matchLabels:
      app: localstack
  template:
    metadata:
      labels:
        app: localstack
    spec:
      containers:
        - name: localstack
          image: localstack/localstack:3.8.1
          ports:
            - containerPort: 4566
          env:
            - name: SERVICES
              value: "sqs"
            - name: DEBUG
              value: "1"
            - name: PERSISTENCE
              value: "1"
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: debugmate-local-secrets
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: debugmate-local-secrets
                  key: AWS_SECRET_ACCESS_KEY
            - name: AWS_DEFAULT_REGION
              value: "eu-central-1"
          volumeMounts:
            - name: localstack-data
              mountPath: /var/lib/localstack
      volumes:
        - name: localstack-data
          persistentVolumeClaim:
            claimName: localstack-data-pvc
