apiVersion: apps/v1
kind: Deployment
metadata:
  name: debugmate-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: debugmate-worker
  template:
    metadata:
      labels:
        app: debugmate-worker
    spec:
      containers:
        - name: debugmate-worker
          image: debugmate-worker:0.1.6-local
          imagePullPolicy: Never
          env:
            - name: ENVIRONMENT
              value: "local"
            - name: CELERY__BROKER_URL
              valueFrom:
                secretKeyRef:
                  name: debugmate-local-secrets
                  key: CELERY_BROKER_URL
            - name: OPENSEARCH__URL
              valueFrom:
                secretKeyRef:
                  name: debugmate-local-secrets
                  key: OPENSEARCH_URL
            - name: OPENSEARCH__USE_SSL
              value: "false"
            - name: OPENSEARCH__VERIFY_CERTS
              value: "false"
            - name: OPENSEARCH__SSL_ASSERT_HOSTNAME
              value: "false"
            - name: OPENSEARCH__SSL_SHOW_WARN
              value: "false"
          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - celery -A worker.celery_app inspect ping -d celery@$HOSTNAME
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3